export const languages = {
  "zh-CN": {
    name: "zh-CN",
    formattedName: "简体中文",
    resources: {
      youHave: "你有",
      unit: "个",
      jiaozi: "饺子",
      jiaozis: "饺子",
      stop: "。",
      core: "核心饺子",
      cores: "核心饺子",
      addPerSec: "你的饺子每秒增加 $1。",
      jiaoziPerSec: "你每秒获得 $1。",
      money: "饺子币",
      atLeast: "至少需要 $1",
      cannotSale: "暂时不能售出",
      maxAll: "购买最大数量",
      saleDisabled: "暂时不能售出",
      saleTip: "售出所有饺子以换取 $1",
      autoMoney: "你可以自动获得饺子币",
      noSale: "你还没有售出过饺子",
      mostSale: "你一次最多售出过 $1",
      maker: "制造器",
      makers: "制造器",
      jMaker: "饺子制造器",
      jMakers: "饺子制造器",
      cost: "价格:",
      locked: "已锁定",
      unlock: "解锁",
      unlocked: "已解锁",
      production: "生产",
      factory: "工厂",
      factories: "工厂",
      mFactory: "蘸料工厂",
      mFactories: "蘸料工厂",
      statistics: "统计",
      achievement: "成就",
      achievements: "成就",
      normalAch: "普通成就",
      normalAchs: "普通成就",
      secretAch: "隐藏成就",
      secretAchs: "隐藏成就",
      wrapper: "饺子皮",
      stuffing: "饺子馅",
      coll: "收集",
      bigReset: "收集重置",
      _bigReset: "大重置",
      steamer: "蒸笼",
      steamerReset: "蒸笼重置",
      fixSteamer: "修复蒸笼",
      bao: "点击以包饺砸！",
      wrapperDes: "优质饺子皮，使制造器的效率$1。",
      current: "当前",
      reward: "奖励",
      reward_: "奖励:",
      next: "下一级",
      capped: "已达到上限",
      collection: "收集饺子",
      collections: "收集饺子",
      bigResetDes: "制造器已达到上限，但饺子馅给你准备了 $1，你可以在$2后获得！",
      stuffingDes: "优质饺子馅，使你解锁下一级制造器。",
      coreGained: "核心饺子",
      noCores: "不能获得核心饺子",
      crd: "核心饺子",
      brokenSteamer: "蒸笼破损",
      cannotSteamerReset: "你无法进行收集重置",
      reach: "到达",
      sc: "蒸笼币",
      scs: "蒸笼币",
      nc: "挑战",
      ncs: "挑战",
      noActiveChalls: "没有正在进行的挑战",
      universe: "饺子宇宙",
      restart: "重新挑战",
      exit: "退出挑战",
      challHeader: "你正处在$1",
      blob: "Blob",
      newFactory: "解锁新的工厂",
      toUnlockFactory: "以解锁新的蘸料工厂",
      p_nextFactory: "解锁下一级工厂的进度",
      options: "选项",
      saving: "存档",
      visual: "视效",
      gameplay: "游戏玩法",
      challenge: "挑战",
      challenges: "挑战",
      automation: "自动化",
      autobuyer: "自动购买器",
      autobuyers: "自动购买器",
      sus: "蒸笼升级",
      su: "蒸笼升级",
      task: "外卖",
      tasks: "外卖",
      simulation: "模拟",
      branch: "分支",
      branches: "分支",
      collInfo: "你最多可同时激活 $1 (已激活 $2 个)",
      collSteamerTip: "到达 $1 后解锁新的内容",
      deactivateInfo: "下次重置时取消激活所有的饺子",
      curAmount: "当前数量",
      activate: "激活",
      questions: "？？？",
      suHeader: "在每列中，必须从上到下购买升级。",
      scCappedAt: "(在 $1 时达到上限)",
      maxSCmult: "购买最大蒸笼币倍增",
      autoScMult: "自动购买蒸笼币倍增:",
      theme: "主题",
      language: "语言",
      lastestResource: "最新资源",
      updateRate: "刷新率",
      ms: "毫秒",
      notation: "记数法",
      sidebar: "边注栏",
      _iteration_: "饺饺子",
      I_iteration_: "暗黑饺子馅饺子",
      _dragon_: "龙之饺",
      I_dragon_: "恶魔之饺",
      _antimatter_: "反物质饺子",
      I_antimatter_: "物质饺子",
      _cat_: "薛定谔的蒸饺",
      I_cat_: "蒸饺的薛定谔",
      _golden_: "纯金饺",
      I_golden_: "青金石之饺",
      _fast_: "饺子极速版",
      I_fast_: "饺子慢速版",
      _garcinol_: "山竹醇饺",
      I_garcinol_: "**饺子**",
      _fire_: "Jiaozi in the Hole",
      I_fire_: "Jiaozi out the Hole",
      _adofai_: "冰与火之饺",
      I_adofai_: "-2之饺",
      micro: "微型",
      small: "小型",
      mediumSmall: "中小型",
      medium: "中型",
      mediumLarge: "中大型",
      large: "大型",
      giant: "巨型",
      infinity: "无限",
      eternity: "永恒",
      scape: "",
      sc_min: "蒸笼币",
      mixture: "蘸料瓶",
      sause: "酱油",
      salt: "盐",
      vinegar: "醋",
      mixturesInfo: "蘸料由$1等配料制成，它们可以在不同的方面为你提供加成。",
      mixtureInfo: "$1使你的$2",
      and: "和",
      en_comma: "",
      general: "常规",
      bigResetCount: "收集重置",
      bigResetCountStat: "你进行过 $1",
      noBigResetCountStat: "你还没有收集重置过。",
      steamerCount: "蒸笼重置",
      steamerCountStat: "你进行过 $1",
      noSteamerCountStat: "你还没有蒸笼重置过。",
      concludes: "终止",
      concludesSimulation: "终止模拟",
      concludesStat: "你终止过 $1",
      simulations: "模拟次数",
      noConcludesStat: "你还没有终止模拟过。",
      realTime: "现实时间",
      gameTime: "游戏时间",
      ago: "之前",
      wra: "饺子皮",
      stu: "馅",
      you: "你",
      version: "当前版本",
      steamerInfo: "蒸笼因饺子过多而损坏",
      common: "普通",
      uncommon: "罕见",
      rare: "稀有",
      epic: "史诗",
      legendary: "传奇",
      C_1: '增加制造器的效率。',
      C_2: '降低饺子皮的初始价格。',
      C_3: "增加点击获得的饺子。",
      C_4: "你可以获得基于饺子馅的免费饺子皮，并且可以在收集重置后获得多个收集饺子(基于当前饺子币)。",
      C_5: "增加饺子皮的基础乘数。",
      C_6: "增加购买制造器的加成。",
      C_7: "出售时获得更多的饺子币。",
      C_8: "饺子出售不再有软下限，制造器可获得基于当前饺子币数量的加成。",
      C_9: "解锁下一级制造器，出售的需求降低至$1，同时降低饺子馅的初始价格。",
      simulationMilestone: "模拟里程碑",
      simulationMilestones: "模拟里程碑",
      SM_buyingMakerBoost: "购买制造器和工厂的倍数+$1。",
      milestone: "里程碑",
      SM_qols: "终止模拟时保留所有蒸笼升级，解锁外卖、蒸笼币倍增的自动购买器，蒸笼后保留所有收集饺子。",
      nextAt: "下一个需要",
      SM_wrapperBoostFactories: "饺子皮以较低的效果加成前四个蘸料工厂。",
      void: "空",
      excessCol: "收集饺子过多",
      save: "保存",
      load: "加载",
      delete: "删除",
      name: "名称",
      SM_keepChall: "模拟重置后保留所有挑战。",
      SM_autoFactory: "解锁工厂自动购买器。",
      toggleAuto: "切换所有自动购买器状态",
      gWrapper: "纯金饺子皮",
      SM_upgrades: "解锁模拟升级。",
      review: "温故",
      preview: "知新",
      simUpg: "模拟升级",
      simUpgs: "模拟升级",
      expSave: "导出存档",
      impSave: "导入存档",
      hardReset: "硬重置",
      saveGame: "保存游戏",
      chooseSave: "选择存档",
      expAsFile: "导出文件存档",
      impAsFile: "导入文件存档",
      showTimeSinceSave: "显示存档时间:",
      timeSinceSave: "距离上次存档",
      autoSaveDisabled: "自动存档已禁用",
      backupModal: "打开自动备份存界面",
      customName: "自定义存档名称",
      saveName: "存档文件名称",
      setNameTooltip: "自定义名称(最多16个字符，包括空格和连字符)",
      autoSaveInterval: "自动存档间隔",
      openExpOptions: "打开指数记数法设置",
      openAnimationOptions: "打开动画设置",
      openAwayProgressOptions: "打开离线资源显示设置",
      openInfoDisplayOptions: "打开详情设置",
      modifyVisibleTabs: "修改可见标签页",
      relativeColor: "获得的资源基于相对数量用颜色标注:",
      on: "已开启",
      off: "已关闭",
      press: "按住",
      openHotkey: "以打开帮助列表。",
      openConfirmationOptions: "打开确认选项",
      enabled: "已启用",
      disabled: "已禁用",
      hotkey_: "快捷键:",
      automaticTabSwitching: "某些时刻切换标签页(例如进入挑战时):",
      offlineProgress_: "离线进程:",
      offlineTicks: "离线游戏刻",
      offlineRun: "离线时暂停时间:",
      openCatchup: "查看内容合集",
      totalJiaozi: "你共制造了 $1。",
      totalRealTime: "你共玩了$1。 (现实时间)",
      saveCreatedStat: "本存档在的创建时间为$1。 ($2之前)",
      fastestCollReset: "你最快的收集重置时间为$1。",
      noFastestCollReset: "你没有最快的收集重置时间。",
      thisCollTime: "你本次收集中花费了$1。",
      fastestSteamerReset: "你最快的蒸笼时间为$1。",
      noFastestSteamerReset: "你没有最快的蒸笼时间。",
      thisSteamerTime: "你在本次蒸笼中花费了$1。",
      fastestSimulationReset: "你最快的模拟时间为$1。",
      noFastestSimulationReset: "你没有最快的模拟时间。",
      thisSimulationTime: "你在本次模拟中花费了$1。",
      year: "年",
      day: "天",
      hour: "小时",
      minute: "分钟",
      second: "秒",
      hideCompletedRows: "隐藏已完成的行:",
      autoAchieve: "自动成就:",
      achievementsBoost: "成就提供了以下的加成:",
      complete: "完成",
      completed: "已完成",
      running: "进行中",
      start: "开始",
      takeoutOrders: "外卖订单",
      takeaway: "外卖",
      auto_: "自动:",
      pauseAutobuyers: "暂停自动购买器",
      resumeAutobuyers: "恢复自动购买器",
      allAutos: "所有自动购买器",
      enable: "启用",
      disable: "禁用",
      buysSingles: "购买单个",
      buysMax: "购买最大数量",
      autoColl: "自动收集",
      collection_x_highest: "基于最高饺子币数量的倍数",
      collection_time: "间隔一定的秒数",
      collection_amount: "到达一定的收集数量",
      scMultiplier: "蒸笼币倍增器",
      currentSetting: "▼ 当前设置: ▼",
      dynamicAmount: "动态数值",
      autofixSteamer: "自动修复蒸笼",
      steamer_x_highest: "基于最高蒸笼币数量的倍数",
      steamer_time: "间隔一定的秒数",
      steamer_amount: "到达一定的蒸笼币",
      autoSell: "自动售出",
      sale_x_highest: "基于最高饺子币数量的倍数",
      sale_time: "间隔一定的时间",
      sale_amount: "到达一定的饺子币",
      stuffingAutobuyer: "饺子馅自动购买器",
      lockedC1: "已锁定 (挑战1)",
      wrapperAutobuyer: "饺子皮自动购买器",
      autobuyerIntervalUpg: "缩短$1的间隔",
      currentInterval: "当前间隔",
      instant: "1游戏刻",
      currentBulk: "当前批量",
      unlimited: "无限",
      unlockAutobuyer: "共需要 $1 个饺子币",
      firstSimulation: "          蒸笼币溢出，饺子宇宙正处于崩溃状态……",
      bigResetChall: "收集重置后不能",
      gainColl: "获得收集饺子",
      collToGain: "收集重置以获得",
      currentAdj: "当前",
      peak: "峰值",
      min: "分钟",
      atPeak: "在$1时达到峰值",
      steamerTo: "修复蒸笼以",
      completeChall: "完成挑战",
      steamerToGain: "修复蒸笼以获得",
      atPeak: "在 $1时达到峰值",
      collection_short: "收集饺子",
      offlineSimulation: "计算离线进度",
      speedUp: "加速",
      skip: "跳过",
      timeSimulated: "已计算$1",
      ticksDone: "游戏刻",
      timeLeft: "剩余时间",
      day_short: "天",
      ach11: "万恶之源",
      ach12: "酱紫玩？",
      ach13: "三重饺子积分",
      ach14: "有没有上限？如限！",
      ach15: "五等分的制造器",
      ach16: "该刷蒸笼次数了",
      ach17: "制造器.7z",
      ach18: "无限饺子",
      ach21: "饺子plus",
      ach22: "每种饺子都有一个",
      ach23: "易如反掌",
      ach24: "又到了最喜欢的升级环节了",
      ach25: "遥遥领先",
      ach26: "这可能吗？",
      ach27: "菜，就多刷",
      ach28: "饺子管理大师",
      ach31: "饺子分店",
      ach32: "无碍，些许蒸笼币罢了",
      ach33: "最简单的一集",
      ach34: "无限工厂",
      ach35: "梦幻联动",
      ach36: "就差亿点",
      ach37: "排列组合大题",
      ach38: "一去不返",
      offlineProgressInfo: "游戏以较低的精度运行，以便快速计算你离线时获得的资源。如果你想了解相关技术的详细信息，请参阅“游戏帮助”中的“离线进度”条目。如果你不想等待了，想早点玩游戏，你可以点击“加速”按钮，用一半的游戏刻模拟剩下的时间(至少剩下$1个游戏刻)。点击“跳过”按钮后将在$2个游戏刻内计算剩余的离线时间。",
      remaining: "剩余",
      tick: "游戏刻",
      buyOne: "购买一个",
      ach21_d: "获得你的第一个收集饺子。",
      ach21_r: "收集次数加成制造器。",
      ach22_d: "解锁全部收集饺子。",
      ach23_d: "修复蒸笼。",
      ach24_d: "购买$1个蒸笼升级。",
      ach24_r: "获得$1倍的蒸笼次数。",
      ach26_d: "获得 $1 个饺子。",
      ach27_d: "完成一个挑战。",
      ach28_d: "完成所有挑战。",
      ach31_d: "解锁蘸料工厂。",
      ach32_d: "解锁中型蘸料工厂。",
      ach33_d: "每个外卖都完成一次。",
      ach34_d: "解锁无限蘸料工厂。",
      ach35_d: "终止模拟。",
      ach35_r: "饺子皮的基础乘数增加$1。",
      ach36_d: "获得 $1 蒸笼币。",
      ach36_r: "当前蒸笼币加成收集数量。",
      ach37_d: "同时拥有所有的模拟升级。",
      ach38_d: "开启进阶模拟。",
      chall1: "你不能购买饺子皮。",
      chall2: "饺子币的获取量大幅下降。",
      chall3: "自动购买饺子皮，并且饺子皮的效果提高饺子馅的价格",
      chall4: "你不能激活任何收集饺子，制造器的效果$2。出售的需求提高到$1。",
      chall5: "你不能激活第三行的饺子。 只有$1的饺子皮有效果。",
      chall6: "你只能购买$1个饺子馅，但收集重置次数加成制造器。",
      chall7: "你只能激活$1个收集饺子，购买制造器或饺子皮时，其它制造器或饺子皮效果大幅削弱。",
      chall8: "制造器乘数的指数$1。",
      collocation_: "收集搭配:",
      unlockChallenge: "到达 $1 个饺子以解锁挑战。",
      noDCinfo: "你不能在挑战中获得收集饺子",
      autoRetryChall: "自动重新挑战:",
      showKnownChall: "显示已知的挑战:",
      updateCollectionSetAfterChallenge: "挑战后保存收集搭配:",
      factory_min: "蘸料工厂",
      joule: "焦耳",
      energy: "饺子能量",
      of: "的",
      corePower: "每个核心饺子的功率为 $1。",
      watt: "瓦",
      SU_makerPow: "制造器的乘数$1",
      SU_steamerCountMult: "制造器获得基于蒸笼次数的加成",
      SU_keepWrapper: "收集后保留 $1 的饺子皮",
      SU_scGen: "基于最快的蒸笼时间，被动产生蒸笼币",
      SU_scGen_effect: "每$1产生$2个",
      SU_collectionsMult: "获得 $1 倍的收集饺子",
      SU_commonPower: "普通收集饺子的效果$1",
      SU_keepStuffing: "收集时保留所有饺子馅",
      SU_resetRequirement: "收集不再需要购买所有饺子馅",
      SU_keepCollections_all: "修复蒸笼后保留所有收集饺子",
      SU_keepCollections: "修复蒸笼后保留每种饺子各 $1 个",
      SU_nextMaker: "饺子馅的上限增加 $1",
      SU_scMult: "基于最快的蒸笼时间，获得更多蒸笼币",
      SU_timeBoost: "制造器获得基于当前蒸笼币的加成",
      SU_unlockSteamerAuto: "解锁自动修复蒸笼",
      extend: "扩展蒸笼",
      hasExtended: "蒸笼已扩展",
      SU_coinMult: "将所有来源的蒸笼币 $1",
      away_exponent: "的指数",
      increasedFrom: "从",
      away_to: "增长到",
      okay: "嗯呐",
      dontShow: "下次不再显示此消息",
      saveN: "存档",
      fileName: "存档名称",
      selected: "已选中",
      away_tip: "提示: 点击可隐藏某个资源",
      away_header: "在你离开的$1里:",
      away_header_nothing: "在你离开的$1里... 没有发生任何事.",
      importYourSave: "导入你的存档",
      imp: "导入",
      challengeIds: "挑战序号:",
      infoDisplayOptions: "详情设置",
      awayProgressOptions: "离线资源显示设置",
      awayProgressNote: "提示: 只有资源增加时才会显示。",
      hotkeyList: "快捷键列表",
      buySingleMaker: "购买1个制造器",
      buyMaxMaker: "购买最大制造器",
      _bigResetCount: "收集重置次数",
      _steamerCount: "蒸笼重置次数",
      modifierKey: "修饰键",
      takeaway_mixtures: "需要 $1 个蘸料瓶",
      takeaway_wrapper: "需要 $1 个饺子皮",
      takeaway_steamer: "需要 $1 蒸笼币",
      takeaway_collections: "激活小于 $1 个收集时达到 $2 饺子",
      reviewTemp: "$2获得 $1 的加成",
      requirement: "需求",
      sa11_n: "彩虹之力",
      sa11_d: "解锁彩虹主题。",
      placeholder: "待定",
      concludeSimulation: "终止模拟",
      buyMakerMult: "购买一个制造器的倍数: $1。"
    }
  },
  "en": {
    name: "en",
    formattedName: "English",
    resources: {
      youHave: "You have",
      unit: "",
      jiaozi: "dumpling",
      jiaozis: "dumplings",
      stop: ".",
      core: "Core Dumpling",
      cores: "Core Dumplings",
      addPerSec: "Your dumplings increases by $1 every second.",
      jiaoziPerSec: "You are getting $1 per second.",
      money: "Dumpling Coin",
      atLeast: "At least $1 are required",
      cannotSale: "Dumplings cannot be sold",
      maxAll: "Buy max",
      saleDisabled: "Sell Disabled",
      saleTip: "Sell all the dumplings in exchange for $1",
      autoMoney: "You can automatically gain Dumpling Coins",
      noSale: "You haven't sold dumplings yet",
      mostSale: "You have sold a maximum of $1 at once",
      maker: "Maker",
      makers: "Makers",
      jMaker: "Dumpling Maker",
      jMakers: "Dumpling Makers",
      cost: "Cost:",
      locked: "Locked",
      unlock: "unlock",
      unlocked: "unlocked",
      production: "Production",
      factory: "Factory",
      factories: "Factories",
      mFactory: "Mixture Factory",
      mFactories: "Mixture Factories",
      statistics: "Statistics",
      achievement: "Achievement",
      achievements: "Achievements",
      normalAch: "Normal Achievement",
      normalAchs: "Normal Achievements",
      secretAch: "Secret Achievement",
      secretAchs: "Secret Achievements",
      wrapper: "Dumpling Wrapper",
      coll: "Collection",
      colls: "Collections",
      stuffing: "Dumpling Stuffing",
      bigReset: "Collection Reset",
      _bigReset: "Big Reset",
      steamer: "Steamer",
      steamerReset: "Steamer Reset",
      fixSteamer: "Fix Steamer",
      bao: "Tap to make dumplings!",
      wrapperDes: "Fresh wrappers give you a $1 multiplier to all Makers.",
      current: "Currently",
      reward: "Reward",
      reward_: "Reward:",
      next: "Next",
      capped: "Capped",
      collection: "Dumpling Collection",
      collections: "Dumpling Collections",
      bigResetDes: "Top-tier Maker is unlocked. But you can perform the $2 to gain $1.",
      stuffingDes: "Tasty stuffings allow you to unlock next Maker.",
      coreGained: "CrD Gained",
      noCores: "No CrD Gained",
      crd: "CrD",
      brokenSteamer: "Steamer is Broken",
      cannotSteamerReset: "You can't perform the Steamer Reset",
      reach: "Reach",
      sc: "Steamer Coin",
      scs: "Steamer Coins",
      nc: "Challenge",
      ncs: "Challenges",
      noActiveChalls: "no active challenges",
      universe: "Dumpling Universe",
      restart: "Restart Challenge",
      exit: "Exit Challenge",
      challHeader: "You are currently in $1",
      blob: "Blob",
      newFactory: "Unlock new Mixture Factory",
      toUnlockFactory: "to unlock new Mixture Factory",
      p_nextFactory: "Percentage to unlock next Mixture Factory",
      sc_min: "SC",
      options: "Options",
      saving: "Saving",
      visual: "Visual",
      gameplay: "Gameplay",
      challenge: "Challenge",
      challenges: "Challenges",
      automation: "Automation",
      autobuyer: "Autobuyer",
      autobuyers: "Autobuyers",
      sus: "Steamer Upgrades",
      su: "Steamer Upgrade",
      task: "Takeaway",
      tasks: "Takeaways",
      simulation: "Simulation",
      branch: "Branch",
      branches: "Branches",
      collInfo: "You can activate up to $1 at the same time ($2 activated)",
      collSteamerTip: "Reach $1 to unlock new content",
      deactivateInfo: "Deactivate all Dumpling Collections on next reset",
      curAmount: "Current amount",
      activate: "Activate",
      questions: "???",
      suHeader: "Within each column, the upgrades must be purchased from top to bottom.",
      maxSCmult: "Max Stamer Coin mult",
      scCappedAt: "(Capped at $1)",
      autoScMult: "Autobuy Steamer Coin mult:",
      theme: "Theme",
      language: "Language",
      lastestResource: "Lastest Resource",
      updateRate: "Update rate",
      ms: "ms",
      notation: "Notation",
      sidebar: "Sidebar",
      _iteration_: "Dumpling in Dumpling",
      I_iteration_: "Dark Dumpling in Dark Dumpling",
      _dragon_: "Dragon Dumpling",
      I_dragon_: "Demon Dumpling",
      _antimatter_: "Antimatter Dumpling",
      I_antimatter_: "Matter Dumpling",
      _cat_: "Schrodinger's Steamed Dumpling",
      I_cat_: "Steamed Dumpling's Schrodinger",
      _golden_: "Pure Gold Dumpling",
      I_golden_: "Lapis Lazuli Dumpling",
      _fast_: "Dumpling Speed Edition",
      I_fast_: "Dumpling Slow Edition",
      _garcinol_: "Garcinol Dumpling",
      I_garcinol_: "**Dumpling**",
      _fire_: "Dumpling in the Hole",
      I_fire_: "Dumpling out the Hole",
      _adofai_: "A Dumpling of Fire and Ice",
      I_adofai_: "A Dumpling of -2",
      micro: "Micro",
      small: "Small",
      mediumSmall: "Medium Small",
      medium: "Medium",
      mediumLarge: "Medium Large",
      large: "Large",
      giant: "Giant",
      infinity: "Infinity",
      eternity: "Eternity",
      scape: " ",
      mixture: "Mixture Bottle",
      sause: "Sauses",
      salt: "Salts",
      vinegar: "Vinegars",
      mixturesInfo: "Mixture is made from ingredients such as $1, which can provide you with effects in different ways.",
      mixtureInfo: "$1 provide a multiplier to $2:",
      and: "and",
      en_comma: ",",
      general: "General",
      bigResetCount: "Collection Reset count",
      _bigResetCount: "Collection Reset count",
      bigResetCountStat: "You have $1.",
      noBigResetCountStat: "You have no Collection Reset counts.",
      steamerCount: "Steamer count",
      _steamerCount: "Steamer count",
      steamerCountStat: "You have $1.",
      noSteamerCountStat: "You have no Steamer Reset counts.",
      conclude: "Conclude",
      concludeSimulation: "Conclude the Simulation",
      concludesStat: "You have concluded $1.",
      noConcludesStat: "You have not concluded the Simulation.",
      simulations: "Simulations",
      realTime: "real time",
      gameTime: "game time",
      ago: "ago",
      wra: "wrapper",
      stu: "stuffing",
      you: "You",
      version: "Version",
      steamerInfo: "The steamer has broken due to excess dumplings.",
      common: "Common",
      uncommon: "Uncommon",
      rare: "Rare",
      epic: "Epic",
      legendary: "Legendary",
      C_1: "Give a multiplier to all makers.",
      C_2: "Wrappers are cheaper.",
      C_3: "Dumplings from tap are multiplied.",
      C_4: "You can gain free wrappers from each stuffing, and gained Dumpling Collections are multiplied based on current Dumpling Coins.",
      C_5: "Increase Wrapper's basic multiplier.",
      C_6: "Increase the multiplier for buying maker.",
      C_7: "Gained Dumpling Coins ^x.",
      C_8: "Gained Dumpling Coins will not decrease before reaching most dumplings, all the makers are multiplied based on current Dumpling Coins.",
      C_9: "You can buy next Maker! Stuffings' cost are reduced! You can sell dumplings just when you reach $1!",
      simulationMilestone: "Simulation Milestone",
      simulationMilestones: "Simulation Milestones",
      SM_buyingMakerBoost: "Increase the multiplier for buying a maker and factory by +$1.",
      milestone: "Milestone",
      SM_qols: "You start Simulation with all Steamer Upgrades. Unlock SC multiplier and takeaways autocompleter. Keep all the Dumpling Collections on Steamer.",
      nextAt: "Next at",
      SM_wrapperBoostFactories: "Wrappers affect first four Mixture Factory with greatly reduced effect.",
      void: "Void",
      excessCol: "Dumpling Collections are excess",
      save: "Save",
      load: "Load",
      delete: "Delete",
      name: "name",
      SM_keepChall: "Keep all Challenges on Concluding Simulation.",
      SM_autoFactory: "Unlock Factory autobuyer.",
      toggleAuto: "Toggle all autobuyers",
      gWrapper: "Golden Dumpling Wrapper",
      SM_upgrades: "Unlock Simulation Upgrades.",
      review: "Review",
      preview: "Preview",
      simUpg: "Simulation Upgrade",
      simUpgs: "Simulation Upgrades",
      expSave: "Export save",
      impSave: "Import save",
      hardReset: "RESET THE GAME",
      saveGame: "Save game",
      chooseSave: "Choose save",
      expAsFile: "Export save as file",
      impAsFile: "Import save from file",
      showTimeSinceSave: "Display time since save:",
      timeSinceSave: "Time since last save",
      backupModal: "Open Automatic Save Backup Menu",
      customName: "Custom save name",
      saveName: "Save file name",
      autoSaveDisabled: "There is nothing left to save.",
      setNameTooltip: "Set a custom name (up to 16 alphanumeric characters, including space and hyphen)",
      autoSaveInterval: "Autosave interval",
      openExpOptions: "Open Exponent Notation Options",
      openAnimationOptions: "Open Animation Options",
      openAwayProgressOptions: "Open Away Progress Options",
      openInfoDisplayOptions: "Open Info Display Options",
      modifyVisibleTabs: "Modify Visible Tabs",
      relativeColor: "Relative prestige gain text coloring:",
      on: "ON",
      off: "OFF",
      press: "Press",
      openHotkey: "to open the hotkey list.",
      openConfirmationOptions: "Open Confirmation Options",
      enabled: "Enabled",
      disabled: "Disabled",
      hotkey_: "Hotkey:",
      automaticTabSwitching: "Switch tabs on some events (e.g. entering challenges):",
      offlineProgress_: "Offline progress:",
      offlineTicks: "Offline ticks",
      offlineRun: "Run suspended time as offline:",
      openCatchup: "View Content Summary",
      totalJiaozi: "You have made a total of $1.",
      totalRealTime: "You have played for $1. (real time)",
      saveCreatedStat: "Your save was created on $1 ($2 ago)",
      fastestCollReset: "Your fastest Collection was $1.",
      noFastestCollReset: "You have no fastest Collection.",
      thisCollTime: "You have spent $1 in this Collection.",
      fastestSteamerReset: "Your fastest Steamer was $1.",
      noFastestSteamerReset: "You have no fastest Steamer.",
      thisSteamerTime: "You have spent $1 in this Steamer.",
      fastestSimulationReset: "Your fastest Simulation was $1.",
      noFastestSimulationReset: "You have no fastest Simulation.",
      thisSimulationTime: "You have spent $1 in this Simulation.",
      year: "year",
      day: "day",
      hour: "hour",
      minute: "minute",
      second: "second",
      hideCompletedRows: "Hide completed rows:",
      autoAchieve: "Auto achievements:",
      achievementsBoost: "Achievements provide a multiplier to",
      complete: "Complete",
      completed: "Completed",
      running: "Running",
      start: "Start",
      takeoutOrders: "Takeout Orders",
      takeaway: "Takeaway",
      auto_: "Auto:",
      pauseAutobuyers: "Pause autobuyers",
      resumeAutobuyers: "Resume autobuyers",
      allAutos: "all autobuyers",
      enable: "Enable",
      disable: "Disable",
      buysSingles: "Buys singles",
      buysMax: "Buys max",
      autoColl: "Automatic Collection",
      collection_x_highest: "X times highest Dump Coins",
      collection_time: "Seconds between Collections",
      collection_amount: "Collect at X Dump Colls",
      scMultiplier: "Steamer Coin Multiplier",
      currentSetting: "▼ Current Setting: ▼",
      dynamicAmount: "Dynamic amount",
      autofixSteamer: "Steamer Autofixer",
      steamer_x_highest: "X times highest SC",
      steamer_time: "Seconds between Steamers",
      steamer_amount: "Fix at X SC",
      autoSell: "Automatic Sell",
      sale_x_highest: "X times highest Dump Coins",
      sale_time: "Seconds between Sales",
      sale_amount: "Sell at X Dump Coins",
      stuffingAutobuyer: "Stuffing Autobuyer",
      lockedC1: "Locked (Challenge 1)",
      wrapperAutobuyer: "Wrapper Autobuyer",
      autobuyerIntervalUpg: "$1 smaller interval",
      currentInterval: "Current interval",
      instant: "Instant",
      currentBulk: "Current Bulk",
      unlimited: "Unlimited",
      unlockAutobuyer: "Requirement: $1 Total Dumpling Coins",
      firstSimulation: "Steamer Coins overflow, and the Dumpling Universe is in a state of collapse…",
      bigResetChall: "You can't gain",
      gainColl: "Dumpling Collections in Challenge.",
      collToGain: "Collect to gain",
      currentAdj: "Current",
      peak: "Peak",
      min: "min",
      atPeak: "at $1",
      steamerTo: "Fix Steamer to",
      completeChall: "Complete the Challenge",
      steamerToGain: "Fix Steamer to gain",
      atPeak: "at $1",
      collection_short: "Dump Coll",
      offlineSimulation: "Calculating offline progress",
      speedUp: "Speed Up",
      skip: "SKIP",
      timeSimulated: "$1 time simulated",
      ticksDone: "ticks done",
      timeLeft: "Time left",
      day_short: "d",
      offlineProgressInfo: "The game is being run at a lower accuracy in order to quickly calculate the resources you gained while you were away. See the How To Play entry on \"Offline Progress\" for technical details. If you are impatient and want to get back to the game sooner, you can click the \"Speed up\" button to simulate the rest of the time with half as many ticks (down to a minimum of $1 ticks remaining). The \"SKIP\" button will instead use all the remaining offline time in $2 ticks.",
      remaining: "Remaining",
      tick: "tick",
      ach11: "Root of all evils",
      ach12: "It's like AD",
      ach13: "Triple Dumpling integral",
      ach14: "Is there a real limit?",
      ach15: "Pentagonal Maker",
      ach16: "It's time to form Steamer counts",
      ach17: "maker.7z",
      ach18: "Infinity Dumpling",
      ach21: "Dumpling plus",
      ach22: "One for each collection",
      ach23: "It’s a piece of cake",
      ach24: "I like upgrades",
      ach25: "Be far ahead",
      ach26: "THIS ACHIEVEMENT DOESN'T EXIST",
      ach27: "Believe Collections",
      ach28: "Master of Dumpling Management",
      ach31: "Do we need Steamer Coins for this?",
      ach32: "No problem, just a few Steamer Coins",
      ach33: "The simplest episode",
      ach34: "Infinity Factory",
      ach35: "Commemorating My Unpublished AD Mod",
      ach36: "Just a little billion close",
      ach37: "Permutation and combination exam",
      ach38: "Be gone forever",
      buyOne: "Buy a ",
      ach21_d: "Get your first Dumpling Collection.",
      ach21_r: "Makers gain a multiplier based on Collection Count.",
      ach22_d: "Unlock all Dumpling Collections.",
      ach23_d: "Fix Steamer.",
      ach24_d: "Buy $1 Steamer Upgrades.",
      ach24_r: "Gain $1 more Steamer counts.",
      ach26_d: "Get $1 dumplings.",
      ach27_d: "Complete a Challenge.",
      ach28_d: "Complete all Challenges.",
      ach31_d: "Unlock Mixture Factory.",
      ach32_d: "Unlock Medium Mixture Factory.",
      ach33_d: "Each takeaway is completed once. ",
      ach34_d: "Unlock Infinity Mixture Factory.",
      ach35_d: "Conclude the Simulation.",
      ach35_r: "Increase Wrapper's basic multiplier by $1.",
      ach36_d: "Get $1 Steamer Coins.",
      ach36_r: "Gained Collections are multiplied based on current SC.",
      ach37_d: "Have all Simulation Upgrades at once.",
      ach38_d: "Start the Advanced Simulation.",
      chall1: "Wrapper is disabled.",
      chall2: "Gained Dumpling Coins has significantly decreased.",
      chall3: "Automatically purchase Dumpling Wrapper, and the price of Dumpling Stuffing increases based on Dumpling Wrapper.",
      chall4: "You can't activate any Dumpling Collections. All Maker's production is $1. The requirement of sale raises to $2.",
      chall5: "You can't activate Dumpling Collections of the third row. And only $1 of Dumpling Wrappers are useful.",
      chall6: "You can only buy $1 Stuffing, but makers gain a multiplier from Collection counts.",
      chall7: "You can only activate $1 Dumpling Collection. Only latest bought Maker or Wrapper is normal.",
      chall8: "The exponent of Maker's multiplier is $1.",
      collocation_: "Collection set:",
      unlockChallenge: "Reach $1 dumplings to unlock challenges.",
      noDCinfo: "You can't gain Dumpling Collections in the challenge.",
      autoRetryChall: "Automatically retry challenges:",
      showKnownChall: "Show all known challenges:",
      updateCollectionSetAfterChallenge: "Save set after the challenges:",
      factory_min: "Mixture F",
      joule: "joule",
      energy: "Dumpling Energy",
      of: "of",
      corePower: "The power of each Core Dumpling is $1.",
      watt: "watt",
      SU_makerPow: "Maker's multiplier is $1",
      SU_steamerCountMult: "Makers gain a multiplier based on Steamer Count",
      SU_keepWrapper: "Keep $1 Wrappers after Collecting.",
      SU_scGen: "Passively generate Steamer Coins based on your fastest Steamer",
      SU_scGen_effect: "$2 every $1",
      SU_collectionsMult: "Gain $1 more Dumpling Collections",
      SU_commonPower: "Common Dumpling Collection's effect is $1",
      SU_keepStuffing: "Keep all Stuffings on Collection",
      SU_resetRequirement: "You can collect without all Stuffing bought",
      SU_keepCollections_all: "Keep all Collections after fixing Steamer",
      SU_keepCollections: "Keep $1 for each Collection after fixing Steamer",
      SU_nextMaker: "Increase Stuffing's cap by $1",
      SU_scMult: "Steamer Coins gain a multplier based on fastest Steamer",
      SU_timeBoost: "Makers are stronger based on current Steamer Coins",
      SU_unlockSteamerAuto: "Unlock Steamer Autofixer",
      extend: "Extend Steamer",
      hasExtended: "Steamer is extended",
      SU_coinMult: "Multiply Steamer Coins from all sources by $1",
      away_exponent: " exponent",
      increasedFrom: " increased from",
      away_to: "to",
      okay: "Okay",
      dontShow: "Don't show this message again",
      saveN: "Save",
      fileName: "File name",
      selected: "Seleted",
      away_tip: "Note: Click an entry to hide it in the future.",
      away_header: "While you were away for $1:",
      away_header_nothing: "While you were away for $1... nothing happened.",
      importYourSave: "Import your save",
      imp: "Import",
      challengeIds: "Challenge IDs:",
      infoDisplayOptions: "Info Display Options",
      awayProgressOptions: "Away Progress Options",
      awayProgressNote: "Note: Selected resources will only show if they've increased.",
      hotkeyList: "Hotkey List",
      buySingleMaker: "Buy 1 Maker",
      buyMaxMaker: "Buy max Makers",
      modifierKey: "Modifier Key",
      takeaway_mixtures: "Requires $1 Mixture Bottles",
      takeaway_wrapper: "Requires $1 Wrappers",
      takeaway_steamer: "Requires $1 Steamer Coins",
      takeaway_collections: "Requires $1 dumplings with less than $2 Collections",
      reviewTemp: "Provide a $1 multplier to $2",
      requirement: "Requirement",
      sa11_n: "Rainbow power",
      sa11_d: "Unlock Rainbow theme.",
      placeholder: "Placeholder",
      buyMakerMult: "Multiplier for buying a maker: $1."
    }
  }
}

